# fly.toml app configuration file generated for diceguild-aragog on 2024-05-19T22:19:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'diceguild-aragog'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 8080
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
